### ISSUE TITLE
Find out why VerifyNativeRecordTest is failing

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#159]
java.lang.NullPointerException
	at electionguard.publish.ElectionRecordFactoryKt.electionRecordFromConsumer(ElectionRecordFactory.kt:63)
	at electionguard.verifier.VerifyNativeRecordTest$verifyNativeRecordTest$1.invokeSuspend(VerifyNativeRecordTest.kt:18)

**Comment by JohnLCaron** [comment]
Just needed to update test data

    val nativeDir = "src/commonTest/data/testElectionRecord/native/"
